"""added nov15

Revision ID: f9914df6f4e3
Revises: 017496a0258a
Create Date: 2023-11-15 07:19:18.859527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9914df6f4e3'
down_revision = '017496a0258a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nov15_sending_1', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('nov15_sending_2', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('nov15_sending_3', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nov15_sending_3')
    op.drop_column('users', 'nov15_sending_2')
    op.drop_column('users', 'nov15_sending_1')
    # ### end Alembic commands ###
