"""sending

Revision ID: 5d677acd29b0
Revises: d99ccde41c9b
Create Date: 2023-11-23 09:12:34.343210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d677acd29b0'
down_revision = 'd99ccde41c9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bf_2_22nov', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bf_2_22nov')
    # ### end Alembic commands ###
