"""bf2

Revision ID: 417f7f33ada5
Revises: 501f1a52bd37
Create Date: 2023-11-09 07:26:09.196499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417f7f33ada5'
down_revision = '501f1a52bd37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('black_friday_sending_2', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('bf_state_2', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bf_state_2')
    op.drop_column('users', 'black_friday_sending_2')
    # ### end Alembic commands ###
