"""sending

Revision ID: d99ccde41c9b
Revises: 8b9cce525ed4
Create Date: 2023-11-23 03:49:42.377597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99ccde41c9b'
down_revision = '8b9cce525ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
