"""sending

Revision ID: b1adfddb9a7f
Revises: 7e6d6a9921bc
Create Date: 2023-11-21 17:01:07.696564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1adfddb9a7f'
down_revision = '7e6d6a9921bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nov21_sending', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nov21_sending')
    # ### end Alembic commands ###
