"""added bf_End

Revision ID: 017496a0258a
Revises: 7cc129f8931d
Create Date: 2023-11-12 15:12:33.055080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017496a0258a'
down_revision = '7cc129f8931d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('black_friday_sending_end', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'black_friday_sending_end')
    # ### end Alembic commands ###
