"""sending

Revision ID: 8df818f6181e
Revises: 8a092e65b31e
Create Date: 2023-11-24 19:59:37.457352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df818f6181e'
down_revision = '8a092e65b31e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nov24_marathon_sending', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nov24_marathon_sending')
    # ### end Alembic commands ###
