"""added bf3

Revision ID: 7cc129f8931d
Revises: 417f7f33ada5
Create Date: 2023-11-09 19:33:58.861362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc129f8931d'
down_revision = '417f7f33ada5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('black_friday_sending_3', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('bf_state_3', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bf_state_3')
    op.drop_column('users', 'black_friday_sending_3')
    # ### end Alembic commands ###
