"""sending

Revision ID: b8325ddc1cc2
Revises: b1adfddb9a7f
Create Date: 2023-11-22 16:01:33.590082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8325ddc1cc2'
down_revision = 'b1adfddb9a7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nov22_sending', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('bf_22nov', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bf_22nov')
    op.drop_column('users', 'nov22_sending')
    # ### end Alembic commands ###
