"""init

Revision ID: dfd4393ebe58
Revises: b8c4caf1859d
Create Date: 2024-04-04 06:20:20.330084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd4393ebe58'
down_revision = 'b8c4caf1859d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
