"""init

Revision ID: 81be2acde6c5
Revises: 81f412b5d810
Create Date: 2024-02-29 08:43:49.044313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81be2acde6c5'
down_revision = '81f412b5d810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_29_feb', sa.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'nov25_marathon_2_sending')
    op.drop_column('users', 'nov15_sending_3')
    op.drop_column('users', 'nov24_2_sending')
    op.drop_column('users', 'black_friday_sending_end')
    op.drop_column('users', 'nov15_sending_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nov15_sending_2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('black_friday_sending_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nov24_2_sending', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nov15_sending_3', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nov25_marathon_2_sending', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'sending_29_feb')
    # ### end Alembic commands ###
