"""empty message

Revision ID: e78698b30ff5
Revises: 52abfd242ec1
Create Date: 2024-04-24 14:11:42.823115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78698b30ff5'
down_revision = '52abfd242ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_24_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_24_april')
    # ### end Alembic commands ###
