"""init

Revision ID: b8c4caf1859d
Revises: 5cc979ba0ed5
Create Date: 2024-03-25 05:11:22.242738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c4caf1859d'
down_revision = '5cc979ba0ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_25_march', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_25_march')
    # ### end Alembic commands ###
