"""comment

Revision ID: 5cc979ba0ed5
Revises: 81be2acde6c5
Create Date: 2024-03-11 03:09:04.658188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc979ba0ed5'
down_revision = '81be2acde6c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_10_march', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_10_march')
    # ### end Alembic commands ###
