"""init

Revision ID: 52abfd242ec1
Revises: dfd4393ebe58
Create Date: 2024-04-04 07:05:32.809857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52abfd242ec1'
down_revision = 'dfd4393ebe58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_4_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_4_april')
    # ### end Alembic commands ###
